program: /home/ws/uwhbq/1_AEGAN/model_aegan_step1.py
name: Bee_AEGAN_step1_090622
method: bayes
metric:
 name: fid_score
 goal: minimize
parameters:
   lr_gen:
       values: [0.001, 0.0005, 0.0001, 0.0005, 0.00001]
   lr_disc:
        values: [0.001, 0.0005, 0.0001, 0.0005, 0.00001]
   latent_dim:
        values: [64, 128, 256, 512, 1024]
   epochs:
        values: [5, 10, 20, 30, 40, 50, 60, 75, 100]
   batch_size:
        values: [4, 8, 16]
   n_critic:
        values: [1,2,3,5,10,15,20]
   lr_enc:
        values: [0.001, 0.0005, 0.0001, 0.0005, 0.00001]
   lr_dec:
        values: [0.001, 0.0005, 0.0001, 0.0005, 0.00001]
   number_epochs_enc_dec:
        values: [1, 3, 5, 7, 10, 15, 20, 25, 30, 40, 50]