program: /home/ws/uwhbq/Bee_AEGAN/model_WGAN_step1_v2.py
name: Bee_WGAN_step1_050622
method: bayes
metric:
 name: fid_score
 goal: minimize
parameters:
   lr_gen:
       values: [0.001, 0.0005, 0.0001, 0.0005, 0.00001]
   lr_disc:
        values: [0.001, 0.0005, 0.0001, 0.0005, 0.00001]
   latent_dim:
        values: [64, 128, 256, 512, 1024]
   epochs:
        values: [5, 10, 20, 30, 40, 50, 60, 75, 100]
   batch_size:
        values: [8, 16, 32, 64]
   n_critic:
        values: [1,2,3,5,10,15,20]